### ISSUE TITLE
Unable to build with gperf 3.1

### ISSUE THREAD

**Issue by reinvantveer** [MotorolaMobilityLLC/nuttx#63]
I'd like this module compiled for the Mods MDK combined with my Motorola Z2 Play but I'm running into some trouble. Some pointers are greatly appreciated!
On Ubuntu 18.04 I am unable to compile, `make` step fails with:

```
Making all in docs
Making all in libs
Making all in parser
  GPERF  hconf.c
  LEX    lconf.c
  YACC   yconf.c
  CC     libkconfig_parser_la-yconf.lo
In file included from yconf.c:242:0:
hconf.gperf:141:1: error: conflicting types for 'kconf_id_lookup'
hconf.gperf:12:31: note: previous declaration of 'kconf_id_lookup' was here
 static const struct kconf_id *kconf_id_lookup(register const char *str, register unsigned int len);
                               ^~~~~~~~~~~~~~~
Makefile:456: recipe for target 'libkconfig_parser_la-yconf.lo' failed
make[3]: *** [libkconfig_parser_la-yconf.lo] Error 1
Makefile:350: recipe for target 'all' failed
make[2]: *** [all] Error 2
Makefile:334: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Makefile:385: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
Using gperf 3.1.1
I found a related issue on http://distortos.org/news/updated-build-instructions-kconfig-frontends/ with the exact same error and a related workaround. However, for Ubuntu 18.04 there is no earlier gperf available other than 3.1.1 judging by the output of apt-cache search madison gperf.

What would be the recommended fix or workaround for this issue?

**Comment by reinvantveer** [comment]
What I'm actually trying to achieve is screen mirroring as described here:
https://www.element14.com/community/groups/moto-mods/blog/2017/02/26/screen-mirroring-a-moto-z-to-hdmi-with-the-moto-mod-development-kit-mdk

But then with a Moto Z2 Play. Is this even possible using the nuttx.tftf firmware?

**Comment by BitWire** [comment]
for me it works with the patch which is described here: http://distortos.org/documentation/building-kconfig-frontends-linux/

I also try to archive display output like described in your link, (I also found it) and i will advise you to get the nuttx.tftf firmware he built, because it works. the nuttx compute firmware i could built from the sources doesn't work at all. and i don't know why

**Comment by BitWire** [comment]
So i got the mdk-compute example to semi-work, i really don't know how. Maybe it was the 'make all' instead of 'make'. So at least the Display output works now. The usb3(.0/.1?) Part isn't working for me...

**Comment by reinvantveer** [comment]
OK thanks, I will try with the pre-compiled nuttx firmware first...

**Comment by reinvantveer** [comment]
Applying the patch works, by the way:
```
~/Documents/Git/motomods/nuttx/misc/tools/kconfig-frontends$ curl -O https://gist.githubusercontent.com/KamilSzczygiel/d16a5d88075939578f7bd8fadd0907aa/raw/1928495cfb6a6141365d545a23d66203222d28c0/kconfig-frontends.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2608  100  2608    0     0  15075      0 --:--:-- --:--:-- --:--:-- 15075
~/Documents/Git/motomods/nuttx/misc/tools/kconfig-frontends$ patch -p1 -i kconfig-frontends.patch 
patching file configure.ac
patching file libs/parser/hconf.gperf
patching file libs/parser/Makefile.am
~/Documents/Git/motomods/nuttx/misc/tools/kconfig-frontends$ autoreconf -fi
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'scripts/.autostuff/scripts'.
libtoolize: copying file 'scripts/.autostuff/scripts/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'scripts/.autostuff/m4'.
libtoolize: copying file 'scripts/.autostuff/m4/libtool.m4'
libtoolize: copying file 'scripts/.autostuff/m4/ltoptions.m4'
libtoolize: copying file 'scripts/.autostuff/m4/ltsugar.m4'
libtoolize: copying file 'scripts/.autostuff/m4/ltversion.m4'
libtoolize: copying file 'scripts/.autostuff/m4/lt~obsolete.m4'
configure.ac:50: installing 'scripts/.autostuff/scripts/compile'
configure.ac:31: installing 'scripts/.autostuff/scripts/missing'
frontends/conf/Makefile.am: installing 'scripts/.autostuff/scripts/depcomp'
~/Documents/Git/motomods/nuttx/misc/tools/kconfig-frontends$ ./configure --enable-mconf --disable-nconf --disable-gconf --disable-qconf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
...
configure: Configured with:
configure: - parser library     : shared (version: 3.12.0)
configure:   - root-menu prompt : Configuration
configure:   - config prefix    : CONFIG_
configure: - frontends          : conf mconf
configure:   - transform name   : s&^&kconfig-&
configure:   - localised        : yes
configure: - install utilities  : yes
configure: - CFLAGS CXXFLAGS    : -Wall 
~/Documents/Git/motomods/nuttx/misc/tools/kconfig-frontends$ make
Making all in docs
Making all in libs
Making all in parser
  CC       libkconfig_parser_la-yconf.lo
In file included from yconf.c:2452:0:
menu.c: In function ‘get_symbol_str’:
menu.c:586:18: warning: ‘jump’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     jump->offset = r->len - 1;
     ~~~~~~~~~~~~~^~~~~~~~~~~~
menu.c:547:19: note: ‘jump’ was declared here
  struct jump_key *jump;
                   ^~~~
  CCLD     libkconfig-parser.la
Making all in lxdialog
  CC       libkconfig_lxdialog_a-checklist.o
  CC       libkconfig_lxdialog_a-inputbox.o
  CC       libkconfig_lxdialog_a-menubox.o
  CC       libkconfig_lxdialog_a-textbox.o
  CC       libkconfig_lxdialog_a-util.o
  CC       libkconfig_lxdialog_a-yesno.o
  AR       libkconfig-lxdialog.a
ar: `u' modifier ignored since `D' is the default (see `U')
Making all in frontends
Making all in conf
  CC       conf-conf.o
  CCLD     conf
Making all in mconf
  CC       mconf-mconf.o
  CCLD     mconf
Making all in scripts
Making all in utils
  CC       gettext-gettext.o
  CCLD     gettext
  GEN      tweak
sudo make install
Making install in docs
 /bin/mkdir -p '/usr/local/share/doc/kconfig-frontends'
 /usr/bin/install -c -m 644 kconfig-language.txt kconfig.txt '/usr/local/share/doc/kconfig-frontends'
...
~/Documents/Git/motomods/nuttx/misc/tools/kconfig-frontends$ sudo ldconfig
